spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/your_database_name
    username: your_database_user
    password: your_database_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
